# TITLE
title: GreenSpice
lang: da-DK

# CONTACT INFO
email: your-email@domain.com
phone: +45 22222222

# DESCRIPTION
description: > # 
    Write an awesome description for your new site here. You can edit this
    line in _config.yml. It will appear in your document head meta (for
    Google search results) and in your feed.xml site description.

# URL
baseurl: "http://greenspice.dk" # the subpath of your site, e.g. /blog
url: "http://greenspice.dk" # the base hostname & protocol for your site


# ------------------- #
# Content fields
# ------------------- #

tagline: Mere end bare peber


# ------------------- #
# Build settings
# ------------------- #

markdown: kramdown
